---
- name: Download 1Password CLI .deb file
  ansible.builtin.get_url:
    url: "https://downloads.1password.com/linux/debian/arm64/stable/1password-cli-arm64-latest.deb"
    dest: "/tmp/1password-cli-arm64-latest.deb"
  tags:
    - linux-full

- name: Install 1Password CLI
  ansible.builtin.apt:
    deb: "/tmp/1password-cli-arm64-latest.deb"
    state: present
  become: true
  tags:
    - linux-full

- name: Clean up downloaded .deb file
  ansible.builtin.file:
    path: "/tmp/1password-cli-arm64-latest.deb"
    state: absent
  tags:
    - linux-full
