---
- name: "Python | Install"
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: true
  tags:
    - linux-full

- name: "Python | Create and activate virtual environment"
  ansible.builtin.command:
    cmd: python3 -m venv /ansible/venv
  args:
    creates: /ansible/venv/bin/python
  environment:
    PATH: "{{ ansible_env.PATH }}:/ansible/venv/bin"  # Ensure the correct Python interpreter is used
  become: no  # No need for privilege escalation
  tags:
    - linux-full

- name: "Python | Install pip packages in virtual environment"
  ansible.builtin.command:
    cmd: "/ansible/venv/bin/python -m pip install {{ item }}"
  loop:
    - shell-gpt==0.9.0  # Install shell-gpt in the virtual environment
    - bpytop
  environment:
    PATH: "{{ ansible_env.PATH }}:/ansible/venv/bin"  # Ensure the correct Python interpreter is used
  become: no  # No need for privilege escalation
  tags:
    - linux-full

- name: "Python | Ensure bpytop directory structure exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    mode: "0755"
    state: directory

- name: "Python | Ensure bpytop directory exists inside .config"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/bpytop"
    mode: "0755"
    state: directory

- name: "Python | Copy bpytop config"
  ansible.builtin.copy:
    src: bpytop.conf
    dest: "{{ ansible_env.HOME }}/.config/bpytop/bpytop.conf"
    mode: "0644"
